### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by Saa007** [okfde/2030watch#32]
When accessing https://www.2030agenda.de/de/links there is trust error in firefox

**Comment by Saa007** [comment]
@knutator2 @greg0r 
Please make sure that the SSL certificate for 2030-watch.de is valid for www.2030-watch.de as well. Thanks

**Comment by jengeb** [comment]
Solved by using the custom www subdomain as main URL and by configuring the DNS settings accordingly (use CNAME for the www subdomain instead of A records). 
Following the [recommendations](https://help.github.com/articles/about-supported-custom-domains/#www-subdomains) of GitHub and the advantages of using a CDN, the www subdomain and CNAMES are used as custom domain. Meaning that from now on the root domain is redirected to www.
